name: presentation
description: Set of tools providing presentation capabilities (tansitions, animation, navigation,...) to a Flutter application
version: 0.0.3
author: Tomek Polanski <polanski.tomek@gmail.com>
homepage: https://github.com/tomaszpolanski/presentation


environment:
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
