
on: push
name: Analyze and Test
jobs:
  build:
    name: Analyze and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: 'v1.12.13+hotfix.6'
    - run: flutter pub get
    - run: flutter analyze
    - run: flutter test
